# Generated by Django 3.0.6 on 2020-05-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ServiceCredit',
        ),
    ]
