# Generated by Django 3.0.6 on 2020-05-30 09:26

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200529_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.AddField(
            model_name='distributor',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='service',
            field=models.CharField(choices=[('credit', 'credit'), ('games', 'games')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='accountId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Distributor'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicecredit',
            name='available',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='servicecredit',
            name='currency',
            field=models.CharField(choices=[('euro', '€'), ('dollar', '$'), ('DZD', 'DZD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='servicecredit',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
