# Generated by Django 3.0.6 on 2020-05-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200530_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='accountIds',
            new_name='accountId',
        ),
    ]
