# Generated by Django 3.0.6 on 2020-05-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200530_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecredit',
            name='currency',
            field=models.CharField(choices=[('€', '€'), ('$', '€'), ('DZD', 'DZD')], max_length=20, null=True),
        ),
    ]
