# Generated by Django 3.0.6 on 2020-05-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200530_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.FloatField(null=True)),
            ],
        ),
    ]
