# Generated by Django 3.0.6 on 2020-05-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tets',
            new_name='Test',
        ),
    ]
