# Generated by Django 3.0.6 on 2020-05-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200530_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('accountId', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
