# Generated by Django 3.0.6 on 2020-05-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200530_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accountId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
    ]
