# Generated by Django 3.0.6 on 2020-05-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200530_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distributor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
