# Generated by Django 3.0.6 on 2020-05-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200530_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.FileField(null=True, upload_to='app/recu'),
        ),
    ]
