# Generated by Django 3.0.6 on 2020-05-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200530_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
