# Generated by Django 3.0.6 on 2020-05-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200530_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distributor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
