# Generated by Django 3.0.6 on 2020-05-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200530_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='ccp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='key',
            field=models.IntegerField(null=True),
        ),
    ]
