# Generated by Django 3.0.6 on 2020-05-30 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200530_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('currency', models.CharField(choices=[('€', '€'), ('$', '$'), ('DZD', 'DZD')], max_length=20, null=True)),
                ('available', models.FloatField(null=True)),
                ('image', models.ImageField(default='defser.png', upload_to='')),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Distributor')),
            ],
        ),
    ]
