# Generated by Django 3.0.6 on 2020-05-30 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_servicegames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
