# Generated by Django 3.0.6 on 2020-05-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_delete_snippet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceGames',
            new_name='ServiceGame',
        ),
    ]
