# Generated by Django 3.0.6 on 2020-06-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200531_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='phone',
            field=models.FloatField(null=True),
        ),
    ]
