# Generated by Django 3.0.6 on 2020-06-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20200601_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
