# Generated by Django 3.0.6 on 2020-06-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20200601_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.FloatField(null=True),
        ),
    ]
