# Generated by Django 3.0.6 on 2020-06-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in process', 'in process'), ('complete', 'complete')], max_length=20, null=True),
        ),
    ]
