# Generated by Django 3.0.6 on 2020-06-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visible_for_buyer',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='visible_for_saller',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in process', 'in process'), ('complete', 'complete')], default='in process', max_length=20, null=True),
        ),
    ]
