# Generated by Django 3.0.6 on 2020-06-05 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20200605_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='service',
        ),
    ]
