# Generated by Django 3.0.6 on 2020-06-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20200605_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='saller',
            new_name='distributor',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='visible_for_saller',
            new_name='visible_for_distributor',
        ),
    ]
