# Generated by Django 3.0.6 on 2020-06-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20200606_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='distributor',
            new_name='saller',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='visible_for_distributor',
            new_name='visible_for_saller',
        ),
    ]
