# Generated by Django 3.0.6 on 2020-06-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20200606_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('credit', 'credit'), ('game', 'game')], max_length=20, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('currency', models.CharField(choices=[('€', '€'), ('$', '$'), ('DZD', 'DZD'), ('Unit', 'Unit')], max_length=20, null=True)),
                ('available', models.FloatField(null=True)),
                ('image', models.ImageField(default='defser.png', upload_to='')),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Distributor')),
            ],
        ),
        migrations.RemoveField(
            model_name='servicegame',
            name='distributor',
        ),
        migrations.DeleteModel(
            name='ServiceCredit',
        ),
        migrations.DeleteModel(
            name='ServiceGame',
        ),
    ]
