# Generated by Django 3.0.6 on 2020-06-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20200607_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='distributor',
            new_name='saller',
        ),
    ]
