# Generated by Django 3.0.6 on 2020-06-07 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20200607_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='saller',
            new_name='distributor',
        ),
    ]
