# Generated by Django 3.0.6 on 2020-06-07 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20200607_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='visible_for_saller',
            new_name='visible_for_distributor',
        ),
    ]
