# Generated by Django 3.0.6 on 2020-06-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='date',
            new_name='time',
        ),
    ]
