# Generated by Django 3.0.6 on 2020-06-09 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_auto_20200609_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
