# Generated by Django 3.0.6 on 2020-06-09 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20200609_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
