# Generated by Django 3.0.6 on 2020-06-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_auto_20200609_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='rip',
            field=models.BigIntegerField(null=True),
        ),
    ]
